// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_brightness_from_path`

Stream<List<BacklightInfo>> watchBacklightEvent() => RustLib.instance.api
    .crateApiQuickSettingsDisplayBrightnessWatchBacklightEvent();

Future<void> changeBrightness({required String name, required int value}) =>
    RustLib.instance.api.crateApiQuickSettingsDisplayBrightnessChangeBrightness(
      name: name,
      value: value,
    );

class BacklightInfo {
  final String name;
  final int brightness;
  final int maxBrightness;

  const BacklightInfo({
    required this.name,
    required this.brightness,
    required this.maxBrightness,
  });

  @override
  int get hashCode =>
      name.hashCode ^ brightness.hashCode ^ maxBrightness.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BacklightInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          brightness == other.brightness &&
          maxBrightness == other.maxBrightness;
}
