// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kitshell/src/rust/frb_generated.dart';

Future<UserInfo> getUserInfo() =>
    RustLib.instance.api.crateApiQuickSettingsWhoamiGetUserInfo();

class UserInfo {
  const UserInfo({
    required this.fullname,
    required this.username,
    required this.hostname,
  });
  final String fullname;
  final String username;
  final String hostname;

  @override
  int get hashCode => fullname.hashCode ^ username.hashCode ^ hostname.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserInfo &&
          runtimeType == other.runtimeType &&
          fullname == other.fullname &&
          username == other.username &&
          hostname == other.hostname;
}
