// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kitshell/src/rust/frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

/// Get current WM used
Future<WindowManager> detectCurrentWm() =>
    RustLib.instance.api.crateApiWmInterfaceBaseDetectCurrentWm();

abstract class WmInterface {}

class LaunchbarItemState {
  const LaunchbarItemState({
    required this.windowId,
    required this.isFocused,
    this.windowTitle,
    this.appId,
    this.workspaceId,
    this.processId,
  });
  final BigInt windowId;
  final String? windowTitle;
  final String? appId;
  final BigInt? workspaceId;
  final int? processId;
  final bool isFocused;

  @override
  int get hashCode =>
      windowId.hashCode ^
      windowTitle.hashCode ^
      appId.hashCode ^
      workspaceId.hashCode ^
      processId.hashCode ^
      isFocused.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LaunchbarItemState &&
          runtimeType == other.runtimeType &&
          windowId == other.windowId &&
          windowTitle == other.windowTitle &&
          appId == other.appId &&
          workspaceId == other.workspaceId &&
          processId == other.processId &&
          isFocused == other.isFocused;
}

enum WindowManager {
  niri,
  unsupported,
}

class WmState {
  const WmState({
    required this.launchbar,
    required this.workspaces,
  });
  final List<LaunchbarItemState> launchbar;
  final List<WorkspaceItemState> workspaces;

  @override
  int get hashCode => launchbar.hashCode ^ workspaces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WmState &&
          runtimeType == other.runtimeType &&
          launchbar == other.launchbar &&
          workspaces == other.workspaces;
}

class WorkspaceItemState {
  const WorkspaceItemState({
    required this.id,
    required this.isFocused,
    this.name,
  });
  final BigInt id;
  final String? name;
  final bool isFocused;

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ isFocused.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceItemState &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isFocused == other.isFocused;
}
