// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

/// Get current WM used
Future<WindowManager> detectCurrentWm() =>
    RustLib.instance.api.crateApiWmInterfaceBaseDetectCurrentWm();

abstract class WmInterface {}

class LaunchbarItemState {
  /// WIndow ID provided by compositor
  final BigInt windowId;

  /// Optional window title
  final String? windowTitle;

  /// App ID (taken from dekstop entry name without ".desktop")
  final String? appId;

  /// Workspace ID this window belongs to
  final BigInt? workspaceId;

  /// Process ID (PID)
  final int? processId;

  /// Whether this window is currently focused
  final bool isFocused;

  const LaunchbarItemState({
    required this.windowId,
    this.windowTitle,
    this.appId,
    this.workspaceId,
    this.processId,
    required this.isFocused,
  });

  @override
  int get hashCode =>
      windowId.hashCode ^
      windowTitle.hashCode ^
      appId.hashCode ^
      workspaceId.hashCode ^
      processId.hashCode ^
      isFocused.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LaunchbarItemState &&
          runtimeType == other.runtimeType &&
          windowId == other.windowId &&
          windowTitle == other.windowTitle &&
          appId == other.appId &&
          workspaceId == other.workspaceId &&
          processId == other.processId &&
          isFocused == other.isFocused;
}

enum WindowManager { niri, unsupported }

class WmState {
  /// Launchbar items containing running apps
  final List<LaunchbarItemState> launchbar;

  /// Workspaces data
  final List<WorkspaceState> workspaces;

  const WmState({required this.launchbar, required this.workspaces});

  @override
  int get hashCode => launchbar.hashCode ^ workspaces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WmState &&
          runtimeType == other.runtimeType &&
          launchbar == other.launchbar &&
          workspaces == other.workspaces;
}

class WorkspaceItemState {
  /// ID of the workspace, should be stable when moving between outputs
  final BigInt id;

  /// Index of the workspace inside this output
  final int idx;

  /// Optional name of workspace
  final String? name;

  /// Whether this workspace is currently focused
  final bool isFocused;

  /// Whether this workspace is active/showing on the output
  final bool isActive;

  const WorkspaceItemState({
    required this.id,
    required this.idx,
    this.name,
    required this.isFocused,
    required this.isActive,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      idx.hashCode ^
      name.hashCode ^
      isFocused.hashCode ^
      isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceItemState &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          idx == other.idx &&
          name == other.name &&
          isFocused == other.isFocused &&
          isActive == other.isActive;
}

class WorkspaceState {
  /// Workspaces in this output
  final List<WorkspaceItemState> items;

  /// Output (monitor name)
  final String? output;

  /// Whether this output have workspace focused
  final bool hasWorkspaceFocused;

  const WorkspaceState({
    required this.items,
    this.output,
    required this.hasWorkspaceFocused,
  });

  @override
  int get hashCode =>
      items.hashCode ^ output.hashCode ^ hasWorkspaceFocused.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceState &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          output == other.output &&
          hasWorkspaceFocused == other.hasWorkspaceFocused;
}
