// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kitshell/src/rust/api/wm_interface/base.dart';
import 'package:kitshell/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_socket`

class Niri {
  const Niri();

  static Future<void> closeWindow({required String windowId}) => RustLib
      .instance
      .api
      .crateApiWmInterfaceNiriNiriCloseWindow(windowId: windowId);

  static Future<void> focusWindow({required String windowId}) => RustLib
      .instance
      .api
      .crateApiWmInterfaceNiriNiriFocusWindow(windowId: windowId);

  static Future<void> switchWorkspace({required String workspaceId}) => RustLib
      .instance
      .api
      .crateApiWmInterfaceNiriNiriSwitchWorkspace(workspaceId: workspaceId);

  static Stream<LaunchbarState> watchLaunchbarEvents() =>
      RustLib.instance.api.crateApiWmInterfaceNiriNiriWatchLaunchbarEvents();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Niri && runtimeType == other.runtimeType;
}
