// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kitshell/src/rust/frb_generated.dart';

Future<List<AppEntry>> getAppmenuItems({required String locale}) => RustLib
    .instance
    .api
    .crateApiAppmenuAppmenuItemsGetAppmenuItems(locale: locale);

Future<String> getIconPath({required String icon}) =>
    RustLib.instance.api.crateApiAppmenuAppmenuItemsGetIconPath(icon: icon);

class AppEntry {
  const AppEntry({
    required this.id,
    required this.name,
    required this.desc,
    required this.exec,
    required this.workingDir,
    required this.runInTerminal,
    required this.icon,
  });
  final String id;
  final String name;
  final String desc;
  final String exec;
  final String workingDir;
  final bool runInTerminal;
  final String icon;

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      desc.hashCode ^
      exec.hashCode ^
      workingDir.hashCode ^
      runInTerminal.hashCode ^
      icon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          desc == other.desc &&
          exec == other.exec &&
          workingDir == other.workingDir &&
          runInTerminal == other.runInTerminal &&
          icon == other.icon;
}
