// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kitshell/src/rust/frb_generated.dart';
import 'package:kitshell/src/rust/lib.dart';

// These functions are ignored because they are not marked as `pub`: `generate_config_file`, `get_temp_dir`, `kill_other_cava_instance`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Stream<CavaState> listenToCava() =>
    RustLib.instance.api.crateApiMprisCavaListenToCava();

class CavaState {
  const CavaState({
    required this.data,
    required this.barCount,
    required this.cavaPid,
  });
  final U8Array32 data;
  final int barCount;
  final int cavaPid;

  @override
  int get hashCode => data.hashCode ^ barCount.hashCode ^ cavaPid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CavaState &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          barCount == other.barCount &&
          cavaPid == other.cavaPid;
}
