// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kitshell/src/rust/frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `eq`, `eq`, `try_from_primitive`, `try_from_primitive`, `try_from`, `try_from`

Future<List<NetworkDevice>> getNetworkDevices() => RustLib.instance.api
    .crateApiQuickSettingsNetworkNetworkDevicesGetNetworkDevices();

/// Enum containing Network's device state, can be used to display
/// connecting status when connecting to wifi
///
/// Description is copied from
/// [NetworkManager docs](https://people.freedesktop.org/~lkundrak/nm-docs/nm-dbus-types.html#NMDeviceState)
enum DeviceState {
  /// the device's state is unknown
  unknown,

  /// the device is recognized, but not managed by NetworkManager
  unmanaged,

  /// the device is managed by NetworkManager, but is not available for use.
  /// Reasons may include the wireless switched off, missing firmware,
  /// no ethernet carrier, missing supplicant or modem manager, etc.
  unavailable,

  /// the device can be activated, but is currently idle
  /// and not connected to a network.
  disconnected,

  /// the device is preparing the connection to the network. This
  /// may include operations like changing the MAC address, setting
  /// physical link properties, and anything else required to connect
  /// to the requested network.
  prepare,

  /// the device is connecting to the requested network. This may include
  /// operations like associating with the WiFi AP, dialing the modem, connecting
  /// to the remote Bluetooth device, etc.
  config,

  /// the device requires more information to continue connecting to the requested
  /// network. This includes secrets like WiFi passphrases, login passwords, PIN
  /// codes, etc.
  needAuth,

  /// the device is requesting IPv4 and/or IPv6 addresses and routing information from the network.
  ipConfig,

  /// the device is checking whether further action is required for the requested network connection.
  /// This may include checking whether only local network access is available, whether a captive portal
  /// is blocking access to the Internet, etc.
  ipCheck,

  /// the device is waiting for a secondary connection (like a VPN) which must activated
  /// before the device can be activated
  secondaries,

  /// the device has a network connection, either local or global.
  activated,

  /// a disconnection from the current network connection was requested, and the device is cleaning up
  /// resources used for that connection. The network connection may still be valid.
  deactivating,

  /// the device failed to connect to the requested network and is cleaning up the connection request
  failed,
}

/// Enum containing part of device type
///
/// Copied from [NetworkManager docs](https://people.freedesktop.org/~lkundrak/nm-docs/nm-dbus-types.html#NMDeviceType)
enum DeviceType {
  /// Network using Ethernet cable
  eth,

  /// Network using Wireless LAN/WiFi
  wifi,

  /// Network using modem (e.g. LTE)
  modem,

  /// Unknown network type
  unknown,
}

class NetworkDevice {
  const NetworkDevice({
    required this.iface,
    required this.devType,
    required this.devState,
  });

  /// Interface name of the device (e.g. wlan0, eth0)
  final String iface;

  /// This device device type
  final DeviceType devType;

  /// This device state
  final DeviceState devState;

  @override
  int get hashCode => iface.hashCode ^ devType.hashCode ^ devState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkDevice &&
          runtimeType == other.runtimeType &&
          iface == other.iface &&
          devType == other.devType &&
          devState == other.devState;
}
