// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kitshell/src/rust/api/quick_settings/network/network_devices.dart';
import 'package:kitshell/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_device_proxy`, `get_nm_proxy`, `get_settings_conn_proxy`, `get_settings_proxy`, `get_wireless_proxy`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectivityState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `eq`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `try_from_primitive`, `try_from`

/// Create new [WlanDevice] instance from specified interface name
Future<WlanDevice> createWlanDevice({required String fromIface}) => RustLib
    .instance
    .api
    .crateApiQuickSettingsNetworkWlanCreateWlanDevice(fromIface: fromIface);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WlanDevice>>
abstract class WlanDevice implements RustOpaqueInterface {
  InternetDeviceState get deviceState;

  String get interface;

  set deviceState(InternetDeviceState deviceState);

  set interface(String interface_);

  Future<void> connectToAp({
    required String ssid,
    required String apPath,
    required bool isApSaved,
    String? password,
  });

  Future<void> disconnect();

  Future<List<AccessPoint>> getAccessPoints();

  /// Get known networks settings hashmap for quick matching
  Future<Map<String, AccessPointSettings>> getKnownNetworksSettings();

  /// Initializes the WLAN device instance
  Future<void> init();

  Stream<InternetDeviceState> monitorDeviceState();

  Future<void> requestScan();
}

class AccessPoint {
  const AccessPoint({
    required this.ssid,
    required this.strength,
    required this.frequency,
    required this.wpaSecurityFlag,
    required this.rsnSecurityFlag,
    required this.apFlagsPrivacy,
    required this.isActive,
    required this.isSaved,
    required this.apPath,
    this.settings,
  });

  /// This access point name/SSID
  final String ssid;

  /// This access point signal strength in percent
  final int strength;

  /// This access point radio frequency
  final WifiFreq frequency;

  /// WPA Security flag for this AP
  final ApSecurityFlag wpaSecurityFlag;

  /// RSN Security flag for this AP
  final ApSecurityFlag rsnSecurityFlag;

  /// AP Privacy flags for this AP
  final bool apFlagsPrivacy;

  /// Whether this AP is currently active and connected
  final bool isActive;

  /// Whether this AP is known/saved
  final bool isSaved;

  /// Access point options for known devices
  /// It is None if the network has not saved yet
  final AccessPointSettings? settings;

  /// DBUS path for this AP
  final String apPath;

  @override
  int get hashCode =>
      ssid.hashCode ^
      strength.hashCode ^
      frequency.hashCode ^
      wpaSecurityFlag.hashCode ^
      rsnSecurityFlag.hashCode ^
      apFlagsPrivacy.hashCode ^
      isActive.hashCode ^
      isSaved.hashCode ^
      settings.hashCode ^
      apPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccessPoint &&
          runtimeType == other.runtimeType &&
          ssid == other.ssid &&
          strength == other.strength &&
          frequency == other.frequency &&
          wpaSecurityFlag == other.wpaSecurityFlag &&
          rsnSecurityFlag == other.rsnSecurityFlag &&
          apFlagsPrivacy == other.apFlagsPrivacy &&
          isActive == other.isActive &&
          isSaved == other.isSaved &&
          settings == other.settings &&
          apPath == other.apPath;
}

class AccessPointSettings {
  const AccessPointSettings({
    required this.autoconnect,
  });

  /// Whether this AP will autoconnect
  final bool autoconnect;

  @override
  int get hashCode => autoconnect.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccessPointSettings &&
          runtimeType == other.runtimeType &&
          autoconnect == other.autoconnect;
}

/// Enum containing AP security flags
///
/// Copied from
/// [NetworkManager docs](https://people.freedesktop.org/~lkundrak/nm-docs/nm-dbus-types.html#NM80211ApSecurityFlags)
enum ApSecurityFlag {
  /// the access point has no special security requirements
  none,

  /// 40/64-bit WEP is supported for pairwise/unicast encryption
  pairWep40,

  /// 104/128-bit WEP is supported for pairwise/unicast encryption
  pairWep104,

  /// TKIP is supported for pairwise/unicast encryption
  pairTkip,

  /// AES/CCMP is supported for pairwise/unicast encryption
  pairCcmp,

  /// 40/64-bit WEP is supported for group/broadcast encryption
  groupWep40,

  /// 104/128-bit WEP is supported for group/broadcast encryption
  groupWep104,

  /// TKIP is supported for group/broadcast encryption
  groupTkip,

  /// AES/CCMP is supported for group/broadcast encryption
  groupCcmp,

  /// WPA/RSN Pre-Shared Key encryption is supported
  keyMgmtPsk,

  /// 802.1x authentication and key management is supported
  keyMgmt8021X,

  /// Unknown value (this is custom value for unknown Key Management)
  unknown,
}

enum WifiFreq {
  freq24Ghz,
  freq5Ghz,
  freq6Ghz,
  freqUnknown,
}
