// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_wireless_proxy`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ApSecurityFlag`, `ConnectivityState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `partial_cmp`, `partial_cmp`, `try_from_primitive`, `try_from`

/// Create new [WlanDevice] instance from specified interface name
Future<WlanDevice> createWlanDevice({required String fromIface}) => RustLib
    .instance
    .api
    .crateApiQuickSettingsNetworkWlanCreateWlanDevice(fromIface: fromIface);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WlanDevice>>
abstract class WlanDevice implements RustOpaqueInterface {
  String get interface;

  set interface(String interface_);

  Future<void> connectToAp({required String ssid, String? password});

  Future<List<AccessPoint>> getAccessPoints();

  /// Initializes the WLAN device instance
  Future<void> init();

  Future<void> requestScan();
}

class AccessPoint {
  /// This access point name/SSID
  final String ssid;

  /// This access point signal strength in percent
  final int strength;

  /// This access point radio frequency
  final WifiFreq frequency;

  /// Whether this AP is currently active and connected
  final bool isActive;

  const AccessPoint({
    required this.ssid,
    required this.strength,
    required this.frequency,
    required this.isActive,
  });

  @override
  int get hashCode =>
      ssid.hashCode ^
      strength.hashCode ^
      frequency.hashCode ^
      isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccessPoint &&
          runtimeType == other.runtimeType &&
          ssid == other.ssid &&
          strength == other.strength &&
          frequency == other.frequency &&
          isActive == other.isActive;
}

enum WifiFreq { freq24Ghz, freq5Ghz, freq6Ghz, freqUnknown }
