// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BatteryData> getBatteryData() =>
    RustLib.instance.api.crateApiBatteryGetBatteryData();

class BatteryData {
  final Float32List capacityPercent;
  final Float32List drainRateWatt;
  final List<BatteryState> status;

  const BatteryData({
    required this.capacityPercent,
    required this.drainRateWatt,
    required this.status,
  });

  @override
  int get hashCode =>
      capacityPercent.hashCode ^ drainRateWatt.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatteryData &&
          runtimeType == other.runtimeType &&
          capacityPercent == other.capacityPercent &&
          drainRateWatt == other.drainRateWatt &&
          status == other.status;
}

enum BatteryState {
  charging,
  discharging,
  full,
  empty,
  unknown,
  ;
}
