// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_brightness`, `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BrightnessData>>
abstract class BrightnessData implements RustOpaqueInterface {
  Uint32List get brightness;

  List<String> get device;

  set brightness(Uint32List brightness);

  set device(List<String> device);

  static Stream<BrightnessData> getBrightnessStream() => RustLib.instance.api
      .crateApiBrightnessBrightnessDataGetBrightnessStream();

  Future<void> setBrightnessAll({required int brightness});
}
