// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'brightness.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `get_brightness`, `new`

@freezed
class BrightnessData with _$BrightnessData {
  const BrightnessData._();
  const factory BrightnessData({
    required List<String> device,
    required Uint32List brightness,
  }) = _BrightnessData;
  static Stream<BrightnessData> getBrightnessStream() => RustLib.instance.api
      .crateApiBrightnessBrightnessDataGetBrightnessStream();
}
