// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<DispInfo>> getDisplayInfo() =>
    RustLib.instance.api.crateApiDisplayInfoGetDisplayInfo();

class DispInfo {
  final String name;
  final int idx;
  final int widthPx;
  final int heightPx;
  final double scale;

  const DispInfo({
    required this.name,
    required this.idx,
    required this.widthPx,
    required this.heightPx,
    required this.scale,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      idx.hashCode ^
      widthPx.hashCode ^
      heightPx.hashCode ^
      scale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DispInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          idx == other.idx &&
          widthPx == other.widthPx &&
          heightPx == other.heightPx &&
          scale == other.scale;
}
