// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kitshell/src/rust/frb_generated.dart';

DispInfo getPrimaryDisplaySize() =>
    RustLib.instance.api.crateApiDisplayInfoGetPrimaryDisplaySize();

class DispInfo {
  const DispInfo({
    required this.widthPx,
    required this.heightPx,
  });
  final int widthPx;
  final int heightPx;

  @override
  int get hashCode => widthPx.hashCode ^ heightPx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DispInfo &&
          runtimeType == other.runtimeType &&
          widthPx == other.widthPx &&
          heightPx == other.heightPx;
}
