// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<WifiData>> getWifiList({required bool rescan}) =>
    RustLib.instance.api.crateApiWifiGetWifiList(rescan: rescan);

Future<bool> connectToWifi({required String ssid, required String password}) =>
    RustLib.instance.api
        .crateApiWifiConnectToWifi(ssid: ssid, password: password);

class WifiData {
  final bool isConnected;
  final String ssid;
  final int signalStrength;

  const WifiData({
    required this.isConnected,
    required this.ssid,
    required this.signalStrength,
  });

  @override
  int get hashCode =>
      isConnected.hashCode ^ ssid.hashCode ^ signalStrength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WifiData &&
          runtimeType == other.runtimeType &&
          isConnected == other.isConnected &&
          ssid == other.ssid &&
          signalStrength == other.signalStrength;
}
