// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IpcMessage`, `IpcReply`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`

class IpcContent {
  final String opt1;
  final String? opt2;
  final String? opt3;
  final String? opt4;
  final String? opt5;

  const IpcContent({
    required this.opt1,
    this.opt2,
    this.opt3,
    this.opt4,
    this.opt5,
  });

  @override
  int get hashCode =>
      opt1.hashCode ^
      opt2.hashCode ^
      opt3.hashCode ^
      opt4.hashCode ^
      opt5.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IpcContent &&
          runtimeType == other.runtimeType &&
          opt1 == other.opt1 &&
          opt2 == other.opt2 &&
          opt3 == other.opt3 &&
          opt4 == other.opt4 &&
          opt5 == other.opt5;
}
